### PR TITLE
Use mocha api instead of `mocha` output

### LINKED ISSUE #18: os tests fails if npm install writes warnings
I added a log for `cmd` `err` & `stderr`
https://github.com/OperationSpark/opspark/blob/57166ea7ca072082d970b3346b13bdf96eff8e1e/controller/test.js#L90-L94

`npm test` usually has a `pretest` hook that runs `npm install`. If there are warnings after installing, it writes them to `stderr` and we reject.

Could try adding ` --loglevel=error` to npm test `cmd`

### LINKED ISSUE #20: JSON reporter stdout is too big to parse if more than ~90 tests
need to use a different reporter? 
json-stream? https://github.com/mochajs/mocha/blob/master/lib/reporters/json-stream.js
custom reporter? https://github.com/mochajs/mocha/wiki/Third-party-reporters

### PR DESCRIPTION
**Pull request by cainwatson**
resolves #20 
resolves #18

### CODE REVIEW

File: controller/test.js [hunk 1]
```diff
@@ -74,67 +81,66 @@ function grabTests(project) {
...
+      console.log(` Passing tests:  ${passes}  `.bgBlue.white);
+      console.log(` Pending tests:  ${pending}  `.bgYellow.black);
+      console.log(` Failing tests:  ${failures}  `.bgRed.white);
+  
+      return { project, testResults };
+    })
+    .catch(error => execAsync(removeProjectTestsCmd)
+      .then(() => Promise.reject(error)))
+    .then(projectResults => execAsync(removeProjectTestsCmd)
+      .then(() => projectResults));
```
Comment (harveysanders) [inline controller/test.js]:
```suggestion
   const removeDeps = () => { // remove the node modules }
    ...
    // fake .finally()
    .then(removeDeps, removeDeps)
```

File: test/helpers/fakeHelpers.js [hunk 2]
```diff
@@ -33,8 +33,12 @@ module.exports.downloadProject = (url, token, directory) => `mkdir ${directory}
 
 module.exports.downloadProjectTests = (url, token, directory) => `mkdir ${directory}/test ${directory}/node_modules`;
```
Comment (harveysanders) [inline test/helpers/fakeHelpers.js]:
```suggestion
// create an empty JSON block so parse doesn't blow up
```

File: test/helpers/fakeHelpers.js [hunk 3]
```diff
@@ -33,8 +33,12 @@ module.exports.downloadProject = (url, token, directory) => `mkdir ${directory}
...
 
-module.exports.downloadProjectPackage = (url, token, directory) => `touch ${directory}/package.json`;
+module.exports.downloadProjectPackage = (url, token, directory) => `echo {} > ${directory}/package.json`;
 
 module.exports.makeTestPass = () => `echo '${dummyTestPass}'`;
 
 module.exports.makeTestFail = () => `echo '${dummyTestFail}'`;
+
+module.exports.reportPass = () => new Promise(res => res(JSON.parse(dummyTestPass)));
```
Comment (harveysanders) [inline test/helpers/fakeHelpers.js]:
```suggestion
module.exports.reportPass = () => Promise.resolve(JSON.parse(dummyTestPass));
```

File: controller/test.js [hunk 4]
```diff
@@ -74,67 +81,66 @@ function grabTests(project) {
...
+      const stackLineTwo = stack[1];
+      const errorInfo = stackLineOne.slice(stackLineOne.indexOf(':'));
+      console.log(`${i + 1}) ${whichTest}`.red.bold.underline);
+      console.log(`> > > ${message}`.red);
+      console.log(`> > > ${errorInfo}`.grey);
+      console.log(`> > > ${stackLineTwo}`.grey);
+    });
+
+    return { pass: false };
+  } else {
```
Comment (harveysanders) [inline controller/test.js]: I think this `else` block is unnecessary.
